### ISSUE TITLE
Post methods should check csrf

### ISSUE THREAD

**Issue by md-5** [SpigotMC/XenforoApiKeys#3]
https://github.com/SpigotMC/XenforoApiKeys/blob/ed020375b3c111d08cd492c87fcf70d4e9390588/upload/library/XenforoApiKeys/ControllerPublic/Index.php#L26

Examples can be found by checking for "isConfirmedPost" usage in the XF codebase

**Comment by md-5** [comment]
I'm actually not sure about the criteria when csrf should or shouldn't be used, it seems inconsistent even in XF

**Comment by jacobsandersen** [comment]
I thought asserting POST was checking CSRF. My bad. The linked PR now checks CSRF after asserting POST.
